version: "3"

services:

  app-1:
    image: example-app
    container_name: "app-1"
    environment:
      MONGO_DATABASE: "exampleappdb"
      VAULT_TOKEN: "password"
      VAULT_HOST: "host.docker.internal"
      VAULT_BACKEND: "example"
    networks:
      - example-net

  app-2:
    image: example-app
    container_name: "app-2"
    environment:
      MONGO_DATABASE: "exampleappdb"
      VAULT_TOKEN: "password"
      VAULT_HOST: "host.docker.internal"
      VAULT_BACKEND: "example"
    networks:
      - example-net

  load-balancer:
    image: example-lb
    container_name: example-lb
    networks:
      - example-net
    ports:
      - 80:80
    depends_on:
      - app-1
      - app-2

  adhoc-mongo:
    image: "mongo:latest"
    container_name: "adhoc-mongo"
    ports:
      - "27019:27017"
    networks:
      - example-net

networks:
  example-net: { }