FROM openjdk:17 as builder
WORKDIR /workspace/app
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY domain domain
COPY rest rest
COPY repository repository
COPY service service
RUN ./mvnw package

FROM openjdk:17
WORKDIR /app
COPY --from=builder /workspace/app/service/target/service-1.0-SNAPSHOT.jar /app
ENTRYPOINT ["java","-Dspring.profiles.active=docker" ,"-jar","service-1.0-SNAPSHOT.jar"]